name = "box-max3"

# الملف الأساسي - الآن المسار صحيح لمجلد src
main = "src/bot.js"

# تاريخ التوافق الأحدث لضمان عمل Node.js compat بشكل كامل
compatibility_date = "2024-09-23"

# تفعيل مكتبات Node.js الضرورية (حل مشكلة crypto و fs)
compatibility_flags = [ "nodejs_compat" ]

[vars]
# المتغيرات التي سيقرأها الكود
BOT_TOKEN = "8513010794:AAH9_FatomlJIIPbCBajnYuRhYy2BcqwBxY"
OWNER_ID = "8311254462"

[observability]
enabled = true
