# اسم المشروع (يفضل أن يطابق الاسم في لوحة تحكم كلوود فلير)
name = "box-max3"

# الملف الأساسي - تأكد أن الملف بهذا الاسم في جذر المستودع
main = "bot.js"

# تاريخ التوافق الأحدث لضمان عمل Node.js compat بشكل كامل
compatibility_date = "2024-09-23"

# تفعيل مكتبات Node.js الضرورية (حل مشكلة crypto و fs)
compatibility_flags = [ "nodejs_compat" ]

[vars]
# المتغيرات التي سيقرأها الكود
BOT_TOKEN = "8513010794:AAH9_FatomlJIIPbCBajnYuRhYy2BcqwBxY"
OWNER_ID = "8311254462"

[observability]
enabled = true
